#-------------------------------
# General Site Settings
# El menu quedo obsoleto a causa del nuevo navegador menu
menu:
- {name: 'Proyectos APP',     url: ''}
- {name: 'Machine Learning',  url: 'ml'}
- {name: 'Deep Learning',     url: 'dl'}
- {name: 'Computer Vision',   url: 'cv'}

#-------------------------------
# Projects APP Section

projects:
- {name: 'Predictor Salarios APP',   url: 'proj-1'}
- {name: 'Predictor de Cargos para Asegurados APP',   url: 'proj-2'}
- {name: 'Clasificadores APP', url: 'proj-3'}
- {name: 'MAGI RECETA Web APP',  url: 'proj-4'}
- {name: 'Reconocimiento Facial APP',  url: 'proj-5'}

#-------------------------------

#-------------------------------
# Machine Learning Section

machine_learning:
- {name: 'Algoritmos de Regresion',   url: 'ml-1'}
- {name: 'Algoritmos de Clasificacion',   url: 'ml-2'}
- {name: 'Algoritmos Agrupamiento', url: 'ml-3'}
- {name: 'Sistemas de Recomendacion',  url: 'ml-4'}
- {name: 'Filtrado Colaborativo',  url: 'ml-5'}

#-------------------------------

#-------------------------------
# Deep Learning Section

deep_learning:
- {name: 'Neural Network Convolutional',   url: 'dl-1'}
- {name: 'RNN',   url: 'dl-2'}
- {name: 'NPL', url: 'dl-3'}
- {name: 'CNN',  url: 'dl-4'}
- {name: 'Redes Neuronales Artificiales',  url: 'dl-5'}

#-------------------------------

#-------------------------------
# Computer Vision Section

computer_vision:
- {name: 'face recognition',   url: 'cv-1'}
- {name: 'box delimiter',   url: 'cv-2'}
- {name: 'slides', url: 'cv-3'}
- {name: 'proximamente',  url: 'cv-4'}
- {name: 'En desarrollo',  url: 'cv-5'}

#-------------------------------
# Contact Section

social:
- {icon: 'linkedin',  link: 'https://linkedin.com/in/ozarate'}
- {icon: 'github',    link: 'https://github.com/waloZarate'}
- {icon: 'twitter',   link: 'https://twitter.com/walozarate'}
- {icon: 'facebook',   link: 'https://facebook.com/osvaldo.zaratec'}
- {icon: 'youtube',   link: 'https://youtube.com'}


# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Personal portfolio powered by Jekyll and GitHub Pages '
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: 

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''

  
